version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: docker/themis-web/Dockerfile
        command: ./main
        environment:
            - WEB_PORT=8080
        ports:
            - 8080:8080